title: Oliver's Blog
author: ocben1
email: ocben1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test run for my new tech blog.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ocben1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
